version: '3.8'

networks:
  m_net: # Defines a custom bridge network named 'm_net'
    driver: bridge

services:
  webapp:
    build:
      context: ./webapp 
    ports:
      - "7003:8080"
    networks:
      - m_net
  
  tgbot:
    build:
      context: ./tgbot
    ports:
      - "7004:3000"
    container_name: tgbot-container
    restart: unless-stopped
    env_file:
      - ./.env 
    volumes:
      - ./tgbot/data:/usr/src/app/data 
    networks:
      - m_net 

volumes:
  tgbot_db_data: # Defines the named volume for data persistence
