version: '3.8'

# Top-level key for defining networks should be 'networks' (plural)
networks:
  m_net: # Your custom network definition
    driver: bridge # You can specify a driver, 'bridge' is the default if not specified

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Ensure nginx.conf exists at this path
      - '/etc/letsencrypt:/etc/letsencrypt' # Ensure this path is correct and accessible
    networks:
      - m_net # Connects this service to the 'm_net' network
    depends_on:
      - webapp # Ensures webapp starts before nginx
  webapp:
    build:
      context: ./webapp # Ensure there's a Dockerfile in the ./webapp directory
    # The internal port of your webapp container should be 80,
    # which is then mapped to port 8080 on the host.
    # If your webapp listens on a different port inside the container, adjust accordingly.
    ports:
      - "8080:8080"
    networks:
      - m_net # Connects this service to the 'm_net' network

# Optional: Define the 'm_net' network as external if it's created outside this compose file
# networks:
#   m_net:
#     external: true
