version: '3.8'

networks:
  m_net: # Defines a custom bridge network named 'm_net'
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - "7003:80"
 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt 
    networks:
      - m_net
    depends_on:
      - webapp
      - tgbot
  webapp:
    build:
      context: ./webapp 

    networks:
      - m_net
  
  tgbot:
    build:
      context: ./tgbot
    container_name: tgbot-container
    restart: unless-stopped
    env_file:
      - ./.env 
    volumes:
      - ./tgbot/data:/usr/src/app/data 
    networks:
      - m_net

volumes:
  tgbot_db_data: 
