version: '3.8'

networks:
  m_net:
    driver: bridge 

services:
  
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt:/etc/letsencrypt 
  #   networks:
  #     - m_net
  #   depends_on:
  #     - webapp
  # webapp:
  #   build:
  #     context: ./webapp 
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - m_net