version: '3.8'

networks:
  m_net: # Defines a custom bridge network named 'm_net'
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt 
    networks:
      - m_net
    depends_on:
      - webapp
      # - tgbot
  webapp:
    build:
      context: ./webapp 
    ports:
      - "8080:8080"
    networks:
      - m_net
  
  # tgbot:
  #   build:
  #     # The build context is now set to './tgbot', meaning Docker will look
  #     # for the Dockerfile in a subdirectory named 'tgbot' relative to this docker-compose.yml
  #     context: ./tgbot
  #     # dockerfile: Dockerfile # Optional: if your Dockerfile has a different name
  #   container_name: tgbot-container
  #   restart: unless-stopped
  #   env_file:
  #     - ./.env # Loads environment variables from a .env file in the same directory as docker-compose.yml
  #   ports:
  #     - "3000:3000" # Maps host port 3000 to container port 3000
  #   volumes:
  #     - ./tgbot/data:/usr/src/app/data # Persists database data
  #   networks:
  #     - m_net # Connects the tgbot service to the 'm_net' network

volumes:
  tgbot_db_data: # Defines the named volume for data persistence
