name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_DIR_VPS }}

            echo ">>> Pulling latest code..."
            git pull origin master # Или ваша основная ветка

            echo ">>> Stopping old containers..."
            docker compose down

            echo ">>> Running database migrations..."
            docker compose run --rm tgbot npm run migrate:up

            echo ">>> Building and starting new containers..."
            docker compose up --build -d

            echo ">>> Pruning old Docker images..."
            docker image prune -af

            echo ">>> Deployment finished!"