name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  update-repo:
    name: update repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_DIR_VPS }}

            echo ">>> Pulling latest code..."
            git pull origin master # Или ваша основная ветка

            echo ">>> Stopping old containers..."
            docker compose down
  run-migrations:
    name: run sqlite migrations
    runs-on: ubuntu-latest
    needs: update-repo
    steps:
      - name: run migration
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_DIR_VPS }}
            docker compose build tgbot 
            docker compose run --rm tgbot npm run migrate:up
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: run-migrations
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_DIR_VPS }}

            echo ">>> Building and starting new containers..."
            docker compose up --build -d

            echo ">>> Pruning old Docker images..."
            docker image prune -af

            echo ">>> Deployment finished!"

